### PR TITLE
#171784081 Setup API documentation using swagger

### PR DESCRIPTION
**Pull request by Francois-MUGOROZI**
#### What does this PR do?
Having swagger for API documentation.

#### Description of Task to be completed?
  Configure swagger to be used as API documentation engine
  Add babel configuration

#### How should this be manually tested?
After cloning the repo, cd into it, type npm install, then type npm start,
open the browser and go to http://localhost:5000/api-docs/json or http://localhost:5000/api-docs
you see the swagger page in JSON for case 1 and swagger-ui in case 2

#### What are the relevant pivotal tracker stories?
[#171784081](https://www.pivotaltracker.com/n/projects/2438874/stories/171784081)

### CODE REVIEW

**Review by irfiacre — APPROVED** [review]

**Review by fordarnold — CHANGES_REQUESTED** [review]
Dear @Francois-MUGOROZI 

Please first resolve the errors that were caught by "Hound CI" before this PR can be merged.

**Comment by kabundege** [comment]
> Dear @Francois-MUGOROZI
> 
> Please first resolve the errors that were caught by "Hound CI" before this PR can be merged.

But hound is giving a prettier error and we I think we don't need prettier, can you guide us on how to resolve that error

**Review by kabundege — APPROVED** [review]
Aside hound-ci error I think you're good

**Comment by fordarnold** [comment]
> > Dear @Francois-MUGOROZI
> > Please first resolve the errors that were caught by "Hound CI" before this PR can be merged.
> 
> But hound is giving a prettier error and we I think we don't need prettier, can you guide us on how to resolve that error

Simply follow the instructions given by Hound... for example _Replace '/' with "/" prettier/prettier_ just means that change the single-quotes into double-quotes in the lines specified.

Also, I believe Hound works with Prettier, and we have already configured Prettier in our codebase, so I believe we do need Prettier.

**Comment by fordarnold** [comment]
> > > Dear @Francois-MUGOROZI
> > > Please first resolve the errors that were caught by "Hound CI" before this PR can be merged.
> > 
> > 
> > But hound is giving a prettier error and we I think we don't need prettier, can you guide us on how to resolve that error
> 
> Simply follow the instructions given by Hound... for example _Replace '/' with "/" prettier/prettier_ just means that change the single-quotes into double-quotes in the lines specified.
> 
> Also, I believe Hound works with Prettier, and we have already configured Prettier in our codebase, so I believe we do need Prettier.

@Francois-MUGOROZI, Hound even shows you the lines to change in your code, so I think you can try to resolve those errors and do a git commit, then push to GitHub.

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Good work sofar @Francois-MUGOROZI . A few change requests though:
- Squash your commit messages
- In addition to your swagger docs implementation, create a simple dummy GET endpoint to test your swagger docs
- I think we can get rid of prettier, it will be conflicting with hound and eslint guidelines

**Review by fordarnold — APPROVED** [review]

**Review by nkalyesubula — APPROVED** [review]

**Pull request merged**
