### PR TITLE
#171784073 Setup Sequelize

### PR DESCRIPTION
**Pull request by benshidanny11**
#### What does this PR do?
- It adds  configuration for setting up sequelize
#### Description of Task to be completed?
- We are going to use sequlize as our ORM on the API. Set up the migrations and models structure, have a dummy user table and model setup to test the whole configuration. Add the various required setup in the README if any is required.
#### How should this be manually tested?
- Clone the repo and checkout to ch-sequelize-setup-171784073
- Check the config file in the server root folder.
#### What are the relevant pivotal tracker stories?
- [171784073](https://www.pivotaltracker.com/story/show/171784073)

### CODE REVIEW

**Review by Francois-MUGOROZI — CHANGES_REQUESTED** [review]
- I think you have to be consistent with es6

- I see that you are using require and import.

- Your PR is on my side poor, can you check out the conventions

**Review by irfiacre — APPROVED** [review]

**Review by kabundege — APPROVED** [review]
Daniel I think aside from François's feedback the remains is the heading tittle of the pr.
The story I'd comes first

**Review by irfiacre — APPROVED** [review]

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Good start @benshidanny11. There are change requests I would like to make:
- In addition to the development DB configurations, add one for test and production environments
- Polish up your PR title and description with a particular focus on the resource I shared with you
- Your commit message isn't inline with what I provided you in the resource. Ensure that you write the correct commit message.
- The folder structure is different from what your team provided. Please correct that too.

**Review by fordarnold — COMMENTED** [review]
Please first fix the errors caught by Hound CI

**Comment by benshidanny11** [comment]
> * I think you have to be consistent with es6
> * I see that you are using require and import.
> * Your PR is on my side poor, can you check out the conventions

Sequelize its self uses es5.

**Comment by benshidanny11** [comment]
> Please first fix the errors caught by Hound CI

I have already done it!

**Review by Francois-MUGOROZI — APPROVED** [review]

**Review by nkalyesubula — APPROVED** [review]

**Pull request merged**
