### PR TITLE
#171912807 deliver winston setup

### PR DESCRIPTION
**Pull request by kabundege**
#### What this PR does?
 - Delivers Winston setup

#### Description of the task to be completed?
 - Logging the events that occur during the processing of an application

#### How should this be tested?
 - This can be tested later when the project is in production or in kickoff development

#### What are the relevant pivotal tracker stories?
 - The story can be found [here](https://www.pivotaltracker.com/story/show/171912807)

#### Screenshots?
N/A
#### Questions?
N/A

### CODE REVIEW

**Review by irfiacre — COMMENTED** [review]
Resolve hound errors.

**Review by fordarnold — APPROVED** [review]

**Comment by kabundege** [comment]
> 
> 
> Resolve hound errors.

Noah said that we are going to remove prettier, because its causing errors

**Comment by fordarnold** [comment]
@kabundege I see the Travis CI tests are failing... Is there a way to fix that?

**Review by irfiacre — APPROVED** [review]

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
@kabundege , please remove the cache files and folders (ie nyc_output), and also make sure that the .env is not pushed

**Review by nkalyesubula — APPROVED** [review]

**Pull request merged**
